// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BDropdown: typeof import('bootstrap-vue-3')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-3')['BDropdownDivider']
    BDropdownItemButton: typeof import('bootstrap-vue-3')['BDropdownItemButton']
    BFormSelect: typeof import('bootstrap-vue-3')['BFormSelect']
    BModal: typeof import('bootstrap-vue-3')['BModal']
    BootstrapModel: typeof import('./src/components/bootstrap-model.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
